export const travelsItems = [
  {
    id: 1,
    pathImg: "/src/assets/home-travel1.png",
    name: "Mount Fuji, ",
    nameSpan: "Tokyo",
    place: "Tokyo, Japan",
    rating: "4.8",
    pathImgTravel: "/src/assets/home-travel1.png",
    nameTravel: "Mount Fuji, ",
    currency: "$",
    price: "350",
    time: "21",
    temperature: "8",
    overviev: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea fugit nemo voluptate aliquam ab mollitia, pariatur labore quos sunt amet quis earum, neque veniam animi, quaerat dolores. Ea neque dolore deleniti nostrum dignissimos. Porro eveniet repudiandae laborum veritatis beatae ex quo delectus perspiciatis deserunt exercitationem autem magnam sit, commodi quos voluptatum, quisquam voluptate culpa quia! Ratione et ipsam voluptatum rem earum in cumque fuga obcaecati vel?",
    details: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea fugit nemo voluptate aliquam ab mollitia, pariatur labore quos sunt amet quis earum, neque veniam animi, quaerat dolores. Ea neque dolore deleniti nostrum dignissimos. Porro eveniet repudiandae laborum veritatis beatae ex quo delectus perspiciatis deserunt exercitationem autem magnam sit, commodi quos voluptatum, quisquam voluptate culpa quia! Ratione et ipsam voluptatum rem earum in cumque fuga obcaecati vel?",
  },
  {
    id: 2,
    pathImg: "/src/assets/home-travel2.png",
    name: "Andes, ",
    nameSpan: "South",
    place: "South, America",
    rating: "4.5",
    pathImgTravel: "/src/assets/home-travel2.png",
    nameTravel: "Andes Mountain",
    currency: "$",
    price: "230",
    time: "8",
    temperature: "16",
    overviev: "This vast mountain range is renowned for its remarkable diversity in terms of topography and climate. It features towering peaks, active volcanoes, deep canyons, expansive plateaus, and lush valleys. The Andes are also home to",
    details: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea fugit nemo voluptate aliquam ab mollitia, pariatur labore quos sunt amet quis earum, neque veniam animi, quaerat dolores. Ea neque dolore deleniti nostrum dignissimos. Porro eveniet repudiandae laborum veritatis beatae ex quo delectus perspiciatis deserunt exercitationem autem magnam sit, commodi quos voluptatum, quisquam voluptate culpa quia! Ratione et ipsam voluptatum rem earum in cumque fuga obcaecati vel?",
  },
  {
    id: 3,
    pathImg: "/src/assets/home-travel1.png",
    name: "Mount Fuji, ",
    nameSpan: "Tokyo",
    place: "Tokyo, Japan",
    rating: "4.8",
    pathImgTravel: "/src/assets/home-travel1.png",
    nameTravel: "Mount Fuji, ",
    currency: "$",
    price: "350",
    time: "21",
    temperature: "8",
    overviev: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea fugit nemo voluptate aliquam ab mollitia, pariatur labore quos sunt amet quis earum, neque veniam animi, quaerat dolores. Ea neque dolore deleniti nostrum dignissimos. Porro eveniet repudiandae laborum veritatis beatae ex quo delectus perspiciatis deserunt exercitationem autem magnam sit, commodi quos voluptatum, quisquam voluptate culpa quia! Ratione et ipsam voluptatum rem earum in cumque fuga obcaecati vel?",
    details: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea fugit nemo voluptate aliquam ab mollitia, pariatur labore quos sunt amet quis earum, neque veniam animi, quaerat dolores. Ea neque dolore deleniti nostrum dignissimos. Porro eveniet repudiandae laborum veritatis beatae ex quo delectus perspiciatis deserunt exercitationem autem magnam sit, commodi quos voluptatum, quisquam voluptate culpa quia! Ratione et ipsam voluptatum rem earum in cumque fuga obcaecati vel?",
  },
  {
    id: 4,
    pathImg: "/src/assets/home-travel2.png",
    name: "Andes, ",
    nameSpan: "South",
    place: "South, America",
    rating: "4.5",
    pathImgTravel: "/src/assets/home-travel2.png",
    nameTravel: "Andes Mountain",
    currency: "$",
    price: "230",
    time: "8",
    temperature: "16",
    overviev: "This vast mountain range is renowned for its remarkable diversity in terms of topography and climate. It features towering peaks, active volcanoes, deep canyons, expansive plateaus, and lush valleys. The Andes are also home to",
    details: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea fugit nemo voluptate aliquam ab mollitia, pariatur labore quos sunt amet quis earum, neque veniam animi, quaerat dolores. Ea neque dolore deleniti nostrum dignissimos. Porro eveniet repudiandae laborum veritatis beatae ex quo delectus perspiciatis deserunt exercitationem autem magnam sit, commodi quos voluptatum, quisquam voluptate culpa quia! Ratione et ipsam voluptatum rem earum in cumque fuga obcaecati vel?",
  },
  {
    id: 5,
    pathImg: "/src/assets/home-travel1.png",
    name: "Mount Fuji, ",
    nameSpan: "Tokyo",
    place: "Tokyo, Japan",
    rating: "4.8",
    pathImgTravel: "/src/assets/home-travel1.png",
    nameTravel: "Mount Fuji, ",
    currency: "$",
    price: "350",
    time: "21",
    temperature: "8",
    overviev: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea fugit nemo voluptate aliquam ab mollitia, pariatur labore quos sunt amet quis earum, neque veniam animi, quaerat dolores. Ea neque dolore deleniti nostrum dignissimos. Porro eveniet repudiandae laborum veritatis beatae ex quo delectus perspiciatis deserunt exercitationem autem magnam sit, commodi quos voluptatum, quisquam voluptate culpa quia! Ratione et ipsam voluptatum rem earum in cumque fuga obcaecati vel?",
    details: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea fugit nemo voluptate aliquam ab mollitia, pariatur labore quos sunt amet quis earum, neque veniam animi, quaerat dolores. Ea neque dolore deleniti nostrum dignissimos. Porro eveniet repudiandae laborum veritatis beatae ex quo delectus perspiciatis deserunt exercitationem autem magnam sit, commodi quos voluptatum, quisquam voluptate culpa quia! Ratione et ipsam voluptatum rem earum in cumque fuga obcaecati vel?",
  },
  {
    id: 6,
    pathImg: "/src/assets/home-travel2.png",
    name: "Andes, ",
    nameSpan: "South",
    place: "South, America",
    rating: "4.5",
    pathImgTravel: "/src/assets/home-travel2.png",
    nameTravel: "Andes Mountain",
    currency: "$",
    price: "230",
    time: "8",
    temperature: "16",
    overviev: "This vast mountain range is renowned for its remarkable diversity in terms of topography and climate. It features towering peaks, active volcanoes, deep canyons, expansive plateaus, and lush valleys. The Andes are also home to",
    details: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea fugit nemo voluptate aliquam ab mollitia, pariatur labore quos sunt amet quis earum, neque veniam animi, quaerat dolores. Ea neque dolore deleniti nostrum dignissimos. Porro eveniet repudiandae laborum veritatis beatae ex quo delectus perspiciatis deserunt exercitationem autem magnam sit, commodi quos voluptatum, quisquam voluptate culpa quia! Ratione et ipsam voluptatum rem earum in cumque fuga obcaecati vel?",
  },
];
